package com.sagalogistics.implementation.database

import com.google.android.gms.tasks.Tasks
import com.google.firebase.database.ktx.database
import com.google.firebase.ktx.Firebase
import com.sagalogistics.lib.database.BarDAO
import com.sagalogistics.lib.models.Bar
import com.sagalogistics.implementation.models.BarImpl
import java.util.concurrent.Callable
import java.util.concurrent.Executors
import java.util.concurrent.Future

/**
 * Implementation of [BarDAO] using a Firebase database and the [BarImpl] class
 *
 * @constructor default constructor
 */
class BarDAOFirebase : BarDAO {
    /**
     * Adds a [bar] to the database
     *
     * If it didn't have a [key][Bar.key] it sets the key generated by Firebase;
     * if it had one it calls [BarDAOFirebase.update]
     */
    override fun add(bar: Bar) {
        val key = bar.key
        if (key == null) {
            val pushedPostRef = barsRef.push()
            bar.key = pushedPostRef.key
            pushedPostRef.setValue(bar)
        } else {
            update(key, bar) //reuse code
        }
    }

    /**
     * Gets a [bar][Bar] from the database identified by its [key],
     * or null if the [bar][Bar] cannot be retrieved
     *
     * Returns an instance of [BarImpl]
     */
    override fun get(key: String): Future<Bar?> {
        val executor = Executors.newSingleThreadExecutor()
        return executor.submit(Callable {
            val task = barsRef.child(key).get()
            Tasks.await(task)
            if(task.isSuccessful) {
                val data = task.result
                val bar: Bar? = data!!.getValue(BarImpl::class.java)
                if (bar != null) {
                    bar.key = data.key
                    return@Callable bar
                }
            }
            return@Callable null
        })
    }

    /**
     * Gets all the [bars][Bar] from the database
     */
    override fun getAll(): Future<Set<Bar>?> {
        val executor = Executors.newSingleThreadExecutor()
        return executor.submit(Callable {
            val task = barsRef.get()
            Tasks.await(task)
            if (task.isSuccessful) {
                val data = task.result
                val result = LinkedHashSet<Bar>()
                if (data != null) {
                    val bars = data.value as Map<*, *>?
                    for ((key) in bars!!){
                        val bar = get(key as String).get()
                        if(bar != null){
                            result.add(bar)
                        }
                    }
                }
                return@Callable result
            }
            return@Callable null
        })
    }

    /**
     * Updates a [bar] in the database
     */
    override fun update(key: String, bar: Bar) {
        val barRef = barsRef.child(key)
        barRef.setValue(bar)
    }

    /**
     * Deletes a [bar][Bar] from the database
     */
    override fun delete(key: String) {
        val barRef = barsRef.child(key)
        barRef.removeValue()
    }

    /**
     * Deletes an [order][com.sagalogistics.lib.models.Order] from all the [bars][Bar]
     */
    override fun deleteOrder(orderKey: String) {
        val executor = Executors.newSingleThreadExecutor()
        executor.submit {
            val task = barsRef.get()
            Tasks.await(task)
            if (task.isSuccessful) {
                val data = task.result
                if (data != null) {
                    val bars = data.value as Map<*, *>?
                    for ((key, value) in bars!!) {
                        val ordersList = (value as Map<*, *>)["orders"] as List<*>
                        for (order in ordersList){
                            if (orderKey == order) {
                                barsRef.child(key as String)
                                    .child("orders")
                                    .child(ordersList.indexOf(order).toString())
                                    .removeValue()
                            }
                        }
                    }
                }
            }
        }
    }

    /**
     * Class fields
     */
    companion object {
        /**
         * Reference to the [Firebase database][Firebase.database]
         */
        private val database = Firebase.database

        /**
         * Reference to the "bars" path in the [database]
         */
        private val barsRef = database.getReference("bars")
    }
}