package com.sagalogistics.implementation.database

import com.google.android.gms.tasks.Tasks
import com.sagalogistics.implementation.models.ItemImpl
import com.google.firebase.database.ktx.database
import com.google.firebase.ktx.Firebase
import com.sagalogistics.lib.database.ItemDAO
import com.sagalogistics.lib.models.Item
import java.util.concurrent.Callable
import java.util.concurrent.Executors
import java.util.concurrent.Future

/**
 * Implementation of [ItemDAO] using a Firebase database and the [ItemImpl] class
 *
 * @constructor default constructor
 */
class ItemDAOFirebase : ItemDAO {
    /**
     * Adds an [item] to the database
     *
     * If it didn't have a [key][Item.key] it sets the key generated by Firebase;
     * if it had one it calls [ItemDAOFirebase.update]
     */
    override fun add(item: Item) {
        val key = item.key
        if (key == null) {
            val pushedPostRef = itemsRef.push()
            item.key = pushedPostRef.key
            pushedPostRef.setValue(item)
        } else {
            update(key, item) //reuse code
        }
    }

    /**
     * Gets an [item][Item] from the database identified by its [key],
     * or null if the [item][Item] cannot be retrieved
     *
     * Returns an instance of [ItemImpl]
     */
    override fun get(key: String): Future<Item?> {
        val executor = Executors.newSingleThreadExecutor()
        return executor.submit(Callable {
            val task = itemsRef.child(key).get()
            Tasks.await(task)
            if(task.isSuccessful){
                val data = task.result
                val item: Item? = data!!.getValue(ItemImpl::class.java)
                if (item != null) {
                    item.key = data.key
                    return@Callable item
                }
            }
            return@Callable null
        })
    }

    /**
     * Gets all the [items][Item] from the database
     */
    override fun getAll(): Future<Set<Item>?> {
        val executor = Executors.newSingleThreadExecutor()
        return executor.submit(Callable {
            val task = itemsRef.get()
            Tasks.await(task)
            if (task.isSuccessful) {
                val data = task.result
                val result = LinkedHashSet<Item>()
                if (data != null) {
                    val items = data.value as Map<*, *>?
                    for ((key) in items!!){
                        val item = get(key as String).get()
                        if(item != null){
                            result.add(item)
                        }
                    }
                }
                return@Callable result
            }
            return@Callable null
        })
    }

    /**
     * Updates an [item] in the database
     */
    override fun update(key: String, item: Item) {
        val itemRef = itemsRef.child(key)
        itemRef.setValue(item)
    }

    /**
     * Deletes an [item][Item] from the database
     */
    override fun delete(key: String) {
        val itemRef = itemsRef.child(key)
        itemRef.removeValue()
    }

    /**
     * Class fields
     */
    companion object {
        /**
         * Reference to the [Firebase database][Firebase.database]
         */
        private val database = Firebase.database

        /**
         * Reference to the "items" path in the [database]
         */
        private val itemsRef = database.getReference("items")
    }
}